feat(actions): auto increment version

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -16,8 +16,8 @@ name: Docker
 #   #   branches: [ "main" ]
 
 on:
-  push:
-    tags: [ 'v*.*.*' ]
+  # push:
+  #   tags: [ 'v*.*.*' ]
   pull_request:
     types: [closed]
     branches:
@@ -105,48 +105,61 @@ jobs:
         # This step uses the identity token to provision an ephemeral certificate
         # against the sigstore community Fulcio instance.
         run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
-  bump-version:
-    if: >
-      github.event.pull_request.merged == true &&
-      startsWith(github.event.pull_request.head.ref, 'post-')
+  bump_version:
+    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'post-')
     runs-on: ubuntu-latest
-    permissions:
-      contents: write
-
     steps:
-      - name: Checkout repo
+      - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Fetch latest tags
-        run: git fetch --tags
-
-      - name: Get latest tag
-        id: get_tag
-        run: |
-          latest=$(git tag --sort=-creatordate | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
-          echo "latest_tag=$latest" >> $GITHUB_OUTPUT
-
-      - name: Bump patch version
-        id: bump_version
-        run: |
-          latest="${{ steps.get_tag.outputs.latest_tag }}"
-          if [[ "$latest" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
-            major="${BASH_REMATCH[1]}"
-            minor="${BASH_REMATCH[2]}"
-            patch="${BASH_REMATCH[3]}"
-            patch=$((patch + 1))
-            new_tag="v$major.$minor.$patch"
-            echo "new_tag=$new_tag"
-            echo "new_tag=$new_tag" >> "$GITHUB_ENV"
-          else
-            echo "Invalid tag format: $latest"
-            exit 1
-
-      - name: Create and push new tag
+      - name: Automated Version Bump
+        uses: phips28/gh-action-bump-version@v11.0.2
+        with:
+          tag-prefix: "v"
         env:
-          NEW_TAG: ${{ steps.bump_version.outputs.new_tag }}
-        run: |
-          git config user.name "GitHub Actions"
-          git config user.email "actions@github.com"
-          git tag "$NEW_TAG"
-          git push origin "$NEW_TAG"
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  # bump-version:
+  #   if: >
+  #     github.event.pull_request.merged == true &&
+  #     startsWith(github.event.pull_request.head.ref, 'post-')
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     contents: write
+
+  #   steps:
+  #     - name: Checkout repo
+  #       uses: actions/checkout@v4
+
+  #     - name: Fetch latest tags
+  #       run: git fetch --tags
+
+  #     - name: Get latest tag
+  #       id: get_tag
+  #       run: |
+  #         latest=$(git tag --sort=-creatordate | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
+  #         echo "latest_tag=$latest" >> $GITHUB_OUTPUT
+
+  #     - name: Bump patch version
+  #       id: bump_version
+  #       run: |
+  #         latest="${{ steps.get_tag.outputs.latest_tag }}"
+  #         if [[ "$latest" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+  #           major="${BASH_REMATCH[1]}"
+  #           minor="${BASH_REMATCH[2]}"
+  #           patch="${BASH_REMATCH[3]}"
+  #           patch=$((patch + 1))
+  #           new_tag="v$major.$minor.$patch"
+  #           echo "new_tag=$new_tag"
+  #           echo "new_tag=$new_tag" >> "$GITHUB_ENV"
+  #         else
+  #           echo "Invalid tag format: $latest"
+  #           exit 1
+
+  #     - name: Create and push new tag
+  #       env:
+  #         NEW_TAG: ${{ steps.bump_version.outputs.new_tag }}
+  #       run: |
+  #         git config user.name "GitHub Actions"
+  #         git config user.email "actions@github.com"
+  #         git tag "$NEW_TAG"
+  #         git push origin "$NEW_TAG"
